import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms & Conditions",
  description:
    "Read the terms and conditions for using Orbyt, the AI-powered content strategy platform by E2 Partners LLC.",
  alternates: {
    canonical: "https://getorbyt.io/terms",
  },
};

export default function TermsPage() {
  return (
    <div className="bg-[#FFF8F0] py-16">
      <div className="max-w-3xl mx-auto px-4">
        <span className="inline-block bg-[#A8A6FF] text-black border-2 border-black shadow-[2px_2px_0px_#000000] rounded-full px-4 py-1 text-sm font-medium mb-4">
          Legal
        </span>
        <h1 className="font-display text-4xl md:text-5xl text-black mb-2">
          TERMS &amp; CONDITIONS
        </h1>
        <p className="text-[#666] mb-10">Last updated: March 5, 2026</p>

        <div className="bg-white border-2 border-black shadow-[4px_4px_0px_#000000] rounded-xl p-6 md:p-8 space-y-8">
          <Section n="1" title="Agreement to Terms">
            By accessing or using the Orbyt platform (the &quot;Service&quot;), operated by E2 Partners LLC (&quot;Company,&quot; &quot;we,&quot; &quot;us,&quot; or &quot;our&quot;), you agree to be bound by these Terms and Conditions (&quot;Terms&quot;). If you do not agree to these Terms, you may not use the Service.
          </Section>

          <Section n="2" title="Description of Service">
            Orbyt is an AI-powered content strategy platform that generates social media strategies, content calendars, and per-post content briefs based on information you provide about your business. The Service uses artificial intelligence to create recommendations and content suggestions.
          </Section>

          <Section n="3" title="Account Registration">
            To use certain features of the Service, you must create an account. You agree to provide accurate, current, and complete information during registration and to keep your account information up to date. You are responsible for safeguarding your account credentials and for all activities that occur under your account.
          </Section>

          <Section n="4" title="Plans and Pricing">
            <div className="space-y-3 mt-2">
              <SubSection title="Free Plan — $0">
                The free plan provides one AI-generated content strategy with a 7-day calendar preview and a limited number of content briefs. No payment is required.
              </SubSection>
              <SubSection title="Starter Plan — $19/month">
                The Starter plan is a monthly subscription that provides up to 5 AI-generated strategies per month, each with a full 30-day content calendar and all content briefs. You may cancel at any time; access continues until the end of the current billing period.
              </SubSection>
              <SubSection title="Pro Plan — $39/month">
                The Pro plan is a monthly subscription that provides unlimited strategy generation, multiple business profiles, and priority AI generation features. You may cancel at any time; access continues until the end of the current billing period.
              </SubSection>
            </div>
          </Section>

          <Section n="5" title="Payments and Refunds">
            <p className="text-sm text-[#333] leading-relaxed mb-3">
              All payments are processed securely through Stripe. By subscribing, you authorize us to charge the applicable monthly fee to your payment method on a recurring basis until you cancel.
            </p>
            <ul className="list-disc list-inside text-sm text-[#333] space-y-2 leading-relaxed">
              <li><strong className="text-black">Starter Plan ($19/month):</strong> Billed monthly. You may cancel at any time. We offer a 7-day money-back guarantee on your first payment — if you are not satisfied, contact us within 7 days for a full refund.</li>
              <li><strong className="text-black">Pro Plan ($39/month):</strong> Billed monthly. You may cancel at any time. We offer a 7-day money-back guarantee on your first payment — if you are not satisfied, contact us within 7 days for a full refund. After the initial period, refunds for the current billing cycle are not provided upon cancellation, but you retain access until the period ends.</li>
            </ul>
          </Section>

          <Section n="6" title="AI-Generated Content">
            <p className="text-sm text-[#333] leading-relaxed mb-3">
              The strategies, content briefs, and recommendations generated by the Service are produced by artificial intelligence and are intended as suggestions and starting points. You acknowledge that:
            </p>
            <ul className="list-disc list-inside text-sm text-[#333] space-y-2 leading-relaxed">
              <li>AI-generated content may not always be accurate, complete, or suitable for your specific needs</li>
              <li>You are solely responsible for reviewing, editing, and approving all content before publishing</li>
              <li>The Company does not guarantee any specific business results from using the generated strategies</li>
              <li>You should use your own judgment and, where appropriate, consult with a professional before acting on any recommendations</li>
            </ul>
          </Section>

          <Section n="7" title="Intellectual Property">
            <div className="space-y-3 mt-2">
              <SubSection title="Your Content">
                You retain ownership of all business information and content you provide to the Service. By using the Service, you grant us a limited license to process this information solely for the purpose of generating your strategies.
              </SubSection>
              <SubSection title="Generated Content">
                Content strategies, briefs, and recommendations generated by the Service are licensed to you for your personal or business use. You may use, modify, and publish the generated content as you see fit.
              </SubSection>
              <SubSection title="Our Platform">
                The Service, including its design, code, algorithms, and branding, is owned by E2 Partners LLC and protected by intellectual property laws. You may not copy, modify, distribute, or reverse-engineer any part of the platform.
              </SubSection>
            </div>
          </Section>

          <Section n="8" title="Acceptable Use">
            <p className="text-sm text-[#333] leading-relaxed mb-3">You agree not to use the Service to:</p>
            <ul className="list-disc list-inside text-sm text-[#333] space-y-2 leading-relaxed">
              <li>Violate any applicable laws or regulations</li>
              <li>Generate content that is defamatory, obscene, fraudulent, or harmful</li>
              <li>Impersonate any person or entity</li>
              <li>Interfere with or disrupt the Service or its infrastructure</li>
              <li>Attempt to gain unauthorized access to any part of the Service</li>
              <li>Use the Service to compete directly with Orbyt</li>
            </ul>
          </Section>

          <Section n="9" title="Limitation of Liability">
            To the maximum extent permitted by law, E2 Partners LLC shall not be liable for any indirect, incidental, special, consequential, or punitive damages arising out of or related to your use of the Service, including but not limited to loss of revenue, loss of data, or business interruption. Our total liability for any claim arising from the Service shall not exceed the amount you paid to us in the twelve (12) months preceding the claim.
          </Section>

          <Section n="10" title="Disclaimer of Warranties">
            The Service is provided &quot;as is&quot; and &quot;as available&quot; without warranties of any kind, whether express or implied, including but not limited to implied warranties of merchantability, fitness for a particular purpose, and non-infringement. We do not warrant that the Service will be uninterrupted, error-free, or secure.
          </Section>

          <Section n="11" title="Termination">
            We may suspend or terminate your access to the Service at any time for violation of these Terms or for any other reason at our discretion. You may delete your account at any time by contacting us. Upon termination, your right to use the Service ceases immediately.
          </Section>

          <Section n="12" title="Governing Law">
            These Terms shall be governed by and construed in accordance with the laws of the United States. Any disputes arising from these Terms or the Service shall be resolved through binding arbitration in accordance with the rules of the American Arbitration Association.
          </Section>

          <Section n="13" title="Changes to Terms">
            We reserve the right to modify these Terms at any time. We will notify you of material changes by posting the updated Terms on this page and updating the &quot;Last updated&quot; date. Your continued use of the Service after changes constitutes acceptance of the revised Terms.
          </Section>

          <Section n="14" title="Contact Us">
            <p className="text-sm text-[#333] leading-relaxed mb-3">If you have any questions about these Terms, please contact us:</p>
            <div className="bg-[#A8A6FF]/20 border-2 border-black rounded-xl p-4 shadow-[2px_2px_0px_#000000]">
              <p className="text-sm font-bold text-black">E2 Partners LLC</p>
              <p className="text-sm text-[#333]">
                Email: <a href="mailto:hello@e2partners.co" className="text-[#918EFA] underline font-medium">hello@e2partners.co</a>
              </p>
            </div>
          </Section>
        </div>
      </div>
    </div>
  );
}

function Section({ n, title, children }: { n: string; title: string; children: React.ReactNode }) {
  return (
    <section>
      <h2 className="font-display text-xl text-black mb-3">{n}. {title}</h2>
      {typeof children === "string" ? (
        <p className="text-sm text-[#333] leading-relaxed">{children}</p>
      ) : (
        children
      )}
    </section>
  );
}

function SubSection({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <div>
      <h3 className="text-sm font-bold text-black mb-1">{title}</h3>
      <p className="text-sm text-[#333] leading-relaxed">{children}</p>
    </div>
  );
}
